"""Carve a tiny subset out of a converted dataset, for the pipeline smoke test.

The point of the smoke test is to prove the code can learn at all: train on a
handful of images and check the model memorises them. Validation deliberately
points at the same images — we want to see the loss collapse and mAP go near 1.0.
A model that cannot overfit twenty images will not learn four thousand, and
finding that out here costs minutes instead of a booked GPU window.

Usage:
    python src/data/make_subset.py --src data/processed/cardd_det --dst data/processed/smoke_det -n 20
"""

import argparse
import random
import shutil
from pathlib import Path

CLASS_NAMES = ["dent", "scratch", "crack", "glass shatter", "lamp broken", "tire flat"]


def link_or_copy(src, dst):
    if dst.exists():
        return
    try:
        dst.hardlink_to(src)
    except (OSError, NotImplementedError):
        shutil.copy2(src, dst)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", required=True, type=Path, help="converted dataset, e.g. data/processed/cardd_det")
    ap.add_argument("--dst", required=True, type=Path, help="where to write the subset")
    ap.add_argument("-n", type=int, default=20, help="how many images")
    ap.add_argument("--split", default="train", help="which split to draw from")
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    label_dir = args.src / "labels" / args.split
    image_dir = args.src / "images" / args.split

    # Only images that actually carry annotations — background images teach the
    # smoke test nothing.
    labelled = sorted(p for p in label_dir.glob("*.txt") if p.stat().st_size > 0)
    if len(labelled) < args.n:
        raise SystemExit(f"Only {len(labelled)} annotated images in {label_dir}")

    random.seed(args.seed)
    picked = random.sample(labelled, args.n)

    if args.dst.exists():
        shutil.rmtree(args.dst)

    for split in ("train", "val"):
        (args.dst / "images" / split).mkdir(parents=True, exist_ok=True)
        (args.dst / "labels" / split).mkdir(parents=True, exist_ok=True)

    for label_path in picked:
        image_path = next(image_dir.glob(label_path.stem + ".*"))
        for split in ("train", "val"):
            link_or_copy(image_path, args.dst / "images" / split / image_path.name)
            shutil.copy2(label_path, args.dst / "labels" / split / label_path.name)

    yaml_lines = [
        "# Smoke-test subset — training and validation are the same images on purpose.",
        "# Generated by src/data/make_subset.py; not a real evaluation set.",
        f"path: {args.dst.resolve().as_posix()}",
        "train: images/train",
        "val: images/val",
        "",
        "names:",
    ] + [f"  {i}: {name}" for i, name in enumerate(CLASS_NAMES)]

    yaml_path = args.dst / "dataset.yaml"
    yaml_path.write_text("\n".join(yaml_lines) + "\n", encoding="utf-8")

    instances = sum(len([l for l in p.read_text(encoding="utf-8").splitlines() if l.strip()]) for p in picked)
    print(f"  {args.n} images, {instances} instances -> {args.dst}")
    print(f"  dataset config: {yaml_path}")


if __name__ == "__main__":
    main()
